const YTAI_BASE = 'https://youtube-transcript.ai'
const TIMESTAMP_LINE = /^\[(\d{1,2}:\d{2}(?::\d{2})?)\]\s*(.+)$/

function parseClockTimestamp(value) {
  const parts = value.split(':').map((part) => Number.parseInt(part, 10))
  if (parts.some((part) => Number.isNaN(part))) return null
  if (parts.length === 2) return parts[0] * 60 + parts[1]
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2]
  return null
}

function interpolateWords(segment) {
  const text = (segment.text ?? '').trim()
  if (!text) return []

  const wordTokens = text.split(/\s+/).filter(Boolean)
  const duration = Math.max(segment.duration ?? 2, 0.1)
  const totalWeight = wordTokens.reduce((sum, word) => sum + Math.max(word.length, 1), 0)
  let cursor = segment.offset ?? 0

  return wordTokens.map((word) => {
    const weight = Math.max(word.length, 1) / totalWeight
    const wordDuration = duration * weight
    const entry = { text: word, offset: cursor, duration: wordDuration }
    cursor += wordDuration
    return entry
  })
}

export function parseYoutubeTranscriptAiMarkdown(markdown) {
  const lines = markdown.split('\n')
  const raw = []

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith('---')) continue
    if (trimmed.startsWith('Source video:')) continue
    if (trimmed.startsWith('Language:')) continue
    if (trimmed.startsWith('Other available languages:')) continue
    if (trimmed.startsWith('To request a specific language:')) continue
    if (trimmed.startsWith('Generated by')) continue
    if (trimmed.startsWith('Interactive version')) continue

    const match = trimmed.match(TIMESTAMP_LINE)
    if (!match) continue

    const offset = parseClockTimestamp(match[1])
    const text = match[2].trim()
    if (offset == null || !text) continue

    raw.push({ offset, text })
  }

  if (raw.length === 0) {
    throw new Error('No captions for this video')
  }

  return raw.map((segment, index) => {
    const nextOffset = raw[index + 1]?.offset
    const duration =
      nextOffset != null
        ? Math.max(nextOffset - segment.offset, 0.5)
        : Math.max(segment.text.split(/\s+/).length * 0.35, 2)

    return {
      text: segment.text,
      offset: segment.offset,
      duration,
      words: interpolateWords({ ...segment, duration }),
    }
  })
}

export async function fetchTranscriptFromYoutubeTranscriptAi(videoId, lang) {
  const url = new URL(`${YTAI_BASE}/transcript/${videoId}.txt`)
  if (lang) url.searchParams.set('lang', lang)

  const response = await fetch(url.toString(), {
    headers: { Accept: 'text/markdown, text/plain, */*' },
  })

  if (response.status === 429) {
    throw new Error('Transcript service rate limited — try again shortly')
  }

  if (!response.ok) {
    throw new Error(`Transcript service failed (${response.status})`)
  }

  const markdown = await response.text()
  if (!markdown.trim() || markdown.trimStart().startsWith('<!DOCTYPE')) {
    throw new Error('Transcript service returned an invalid response')
  }

  return parseYoutubeTranscriptAiMarkdown(markdown)
}

export async function fetchTranscriptWithLangFallback(videoId) {
  for (const lang of ['en', 'de', null]) {
    try {
      const segments = await fetchTranscriptFromYoutubeTranscriptAi(videoId, lang)
      if (segments.length > 0) return segments
    } catch {
      // try next language
    }
  }
  throw new Error('No captions for this video')
}
