import { enrichSegmentWithWords } from './transcriptWords.js'

export const YOUTUBE_TRANSCRIPT_AI_DEFAULT =
  'https://youtube-transcript.ai'

const TIMESTAMP_LINE =
  /^\[(\d{1,2}:\d{2}(?::\d{2})?)\]\s*(.+)$/

function parseClockTimestamp(value) {
  const parts = value.split(':').map((part) => Number.parseInt(part, 10))
  if (parts.some((part) => Number.isNaN(part))) return null
  if (parts.length === 2) return parts[0] * 60 + parts[1]
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2]
  return null
}

export function parseYoutubeTranscriptAiMarkdown(markdown) {
  const lines = markdown.split('\n')
  const raw = []

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith('---')) continue
    if (trimmed.startsWith('Source video:')) continue
    if (trimmed.startsWith('Language:')) continue
    if (trimmed.startsWith('Other available languages:')) continue
    if (trimmed.startsWith('To request a specific language:')) continue
    if (trimmed.startsWith('Generated by')) continue
    if (trimmed.startsWith('Interactive version')) continue

    const match = trimmed.match(TIMESTAMP_LINE)
    if (!match) continue

    const offset = parseClockTimestamp(match[1])
    const text = match[2].trim()
    if (offset == null || !text) continue

    raw.push({ offset, text })
  }

  if (raw.length === 0) {
    throw new Error('No captions for this video')
  }

  return raw.map((segment, index) => {
    const nextOffset = raw[index + 1]?.offset
    const duration =
      nextOffset != null
        ? Math.max(nextOffset - segment.offset, 0.5)
        : Math.max(segment.text.split(/\s+/).length * 0.35, 2)

    return enrichSegmentWithWords({
      text: segment.text,
      offset: segment.offset,
      duration,
    })
  })
}

export function isYoutubeTranscriptAiEnabled(env = {}) {
  const flag = env.YOUTUBE_TRANSCRIPT_AI_ENABLED?.trim().toLowerCase()
  if (flag === 'false' || flag === '0' || flag === 'off') return false
  return true
}

export function getYoutubeTranscriptAiBase(env = {}) {
  return (
    env.YOUTUBE_TRANSCRIPT_AI_BASE?.trim().replace(/\/$/, '') ||
    YOUTUBE_TRANSCRIPT_AI_DEFAULT
  )
}

export async function fetchViaYoutubeTranscriptAi(videoId, env = {}, httpFetch = fetch) {
  if (!isYoutubeTranscriptAiEnabled(env)) {
    throw new Error('youtube-transcript.ai disabled')
  }

  const base = getYoutubeTranscriptAiBase(env)
  const timeoutMs = Number(env.YOUTUBE_TRANSCRIPT_AI_TIMEOUT_MS) || 8000
  const headers = {
    Accept: 'text/markdown, text/plain, */*',
    'User-Agent': 'VoidTube/1.0 (+https://voidtube.pages.dev)',
  }

  const token = env.YOUTUBE_TRANSCRIPT_AI_TOKEN?.trim()
  if (token) {
    headers['X-YTS-Token'] = token
  }

  for (const lang of [env.YOUTUBE_TRANSCRIPT_AI_LANG?.trim(), 'en', 'de', null]) {
    const controller = new AbortController()
    const timer = setTimeout(() => controller.abort(), timeoutMs)

    try {
      const url = new URL(`${base}/transcript/${videoId}.txt`)
      if (lang) url.searchParams.set('lang', lang)

      const response = await httpFetch(url.toString(), {
        headers,
        signal: controller.signal,
      })

      if (response.status === 429) {
        throw new Error('Transcript service rate limited — try again shortly')
      }

      if (!response.ok) continue

      const markdown = await response.text()
      if (!markdown.trim() || markdown.trimStart().startsWith('<!DOCTYPE')) continue

      return parseYoutubeTranscriptAiMarkdown(markdown)
    } catch (err) {
      if (err.name === 'AbortError') {
        throw new Error('Transcript service timed out')
      }
      if (err.message.includes('rate limited')) throw err
    } finally {
      clearTimeout(timer)
    }
  }

  throw new Error('No captions for this video')
}
